# Generated by Django 5.0.2 on 2024-02-28 03:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="test1",
            new_name="TestModel",
        ),
    ]
